version: "3.8"

services:
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - "3307:3306"  
  mongodb:
    image: mongo:4.0.4
    ports:
      - "28017:27017"
    
