version: "3.8"

services:
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - "33060:3306"  
  mongodb:
    image: mongodb/mongodb-community-server
    ports:
      - "28017:27017"
